name: Docker Image CI/CD for Backend

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PORT: ${{ secrets.PORT }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      JSON_WEB_TOKEN_KEY: ${{ secrets.JSON_WEB_TOKEN_KEY }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: roba00/tech-ecommerce-app-backend:latest
          context: ./backend
